---
title: "Assignment 2"
output:
  word_document: default
  html_document: default
date: "2024-10-02"
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Load in packages
library(tidyverse)
library(ggplot2)
library(here)
library(dplyr)

#Read in Boone Data
boone <- read.csv(file = 
    here("./Data Raw/Boone_daily_precip_1980-present_HUC_050500010201_dayMet_split-dates-columns.csv"),
    stringsAsFactors = TRUE)

#Read in Greensboro Data
greensboro <- read.csv(file = 
    here("./Data Raw/Greensboro_daily_precip_1980-present_HUC_030300020105_dayMet_split-dates-columns.csv"),
    stringsAsFactors = TRUE)

#Read in Greenville Data
greenville <- read.csv(file = 
    here("./Data Raw/Greenville_daily_precip_1980-present_HUC_030201030403_dayMet_split-dates-columns.csv"),
    stringsAsFactors = TRUE)
```

```{r Block 1: Boone 1980-1999 vs 2000-2016}
#Boone - 1980-1999
early_boone <- boone %>% 
  filter(year < 2000)

#Calculate moving sum
library(zoo)
moving_sum_early_boone <- rollapply(
  early_boone$Area.Weighted.Mean.Precipitation..mm.per.day., width = 2, 
  FUN = sum, fill = NA, align = "right")

#Turn into a data frame
moving_early_boone <- data.frame(
  Original_Data = early_boone,
  Moving_Sum = moving_sum_early_boone
) %>% 
  filter(Moving_Sum > 0)

#Calculate annual two-day max
movingearly_boone_annual <- moving_early_boone %>% 
  filter(Original_Data.year < 2000) %>% 
  group_by(Original_Data.year) %>% 
  summarise(twoday_max_annual = max(Moving_Sum))

#Calculate return period
rp_early_boone_moving <- moving_early_boone %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(number_events = 3986) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 66 mm

#Plot annual two-day max + return period
ggplot(movingearly_boone_annual, aes(x = Original_Data.year, y = twoday_max_annual)) +
  geom_line() +
  geom_smooth(method = "lm") +
  geom_hline(yintercept = 66, color = "red", linetype = "dashed", size = 1) +
    scale_x_continuous(breaks = seq(1980, 1999, 1)) +
  labs(title = "Annual Maximum Two-Day Precipitation Events for Boone\nfrom 1980-1999",
       x = "Year",
       y = "Depth of precipitation (mm)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

#Boone - 2000-2016
late_boone <- boone %>% 
  filter(year >= 2000)

#Calculate moving sum
moving_sum_late_boone <- rollapply(late_boone$Area.Weighted.Mean.Precipitation..mm.per.day., width = 2, FUN = sum, fill = NA, align = "right")

#Turn into a data frame
moving_late_boone <- data.frame(
  Original_Data = late_boone,
  Moving_Sum = moving_sum_late_boone
) %>% 
  filter(Moving_Sum > 0)

#Calculate annual two-day max
movinglate_boone_annual <- moving_late_boone %>% 
  filter(Original_Data.year >= 2000) %>% 
  group_by(Original_Data.year) %>% 
  summarise(twoday_max_annual = max(Moving_Sum))

#Calculate return period
rp_late_boone_moving <- moving_late_boone %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(number_events = 3460) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 80 mm

#Plot annual two-day max and return period
ggplot(movinglate_boone_annual, aes(x = Original_Data.year, y = twoday_max_annual)) +
  geom_line() +
  geom_smooth(method = "lm") +
  geom_hline(yintercept = 68, color = "red", linetype = "dashed", size = 1) +
  scale_x_continuous(breaks = seq(2000, 2016, 1)) +
    labs(title = "Annual Maximum Two-Day Precipitation Events for Boone\nfrom 2000-2016",
       x = "Year",
       y = "Depth of precipitation (mm)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r Block 2: Greensboro 1980-1999 vs 2000-2016}
#Greensboro, 1980-1999
early_greensboro <- greensboro %>% 
  filter(year < 2000)

#Calculate moving sum
moving_sum_early_greensboro <- rollapply(early_greensboro$Area.Weighted.Mean.Precipitation..mm.per.day., 
                                         width = 2, FUN = sum, fill = NA, 
                                         align = "right")

#Turn into data frame
moving_early_greensboro <- data.frame(
  Original_Data = early_greensboro,
  Moving_Sum = moving_sum_early_greensboro
) %>% 
  filter(Moving_Sum > 0)

#Calculate annual two-day max 
movingearly_greensboro_annual <- moving_early_greensboro  %>% 
  filter(Original_Data.year < 2000) %>% 
  group_by(Original_Data.year) %>% 
  summarise(twoday_max_annual = max(Moving_Sum))

#Calculate return period
rp_early_greensboro_moving <- moving_early_greensboro %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(number_events = 3291) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 55 mm

#Plot annual two-day max and return period
ggplot(movingearly_greensboro_annual, aes(x = Original_Data.year, y = twoday_max_annual)) +
  geom_line() +
  geom_smooth(method = "lm") +
  geom_hline(yintercept = 55, color = "red", linetype = "dashed", size = 1) +
    scale_x_continuous(breaks = seq(1980, 1999, 1)) +
  labs(title = "Annual Maximum Two-Day Precipitation Events for Greensboro\nfrom   1980-1999",
       x = "Year",
       y = "Depth of precipitation (mm)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  

#Greensboro, 2000-2016
late_greensboro <- greensboro %>% 
  filter(year >= 2000)

#Calculate moving sum
moving_sum_late_greensboro <- rollapply(late_greensboro$Area.Weighted.Mean.Precipitation..mm.per.day., 
                                        width = 2, FUN = sum, fill = NA, 
                                        align = "right")

#Turn into data frame
moving_late_greensboro <- data.frame(
  Original_Data = late_greensboro,
  Moving_Sum = moving_sum_late_greensboro
) %>% 
  filter(Moving_Sum > 0)

#Calculate annual two-day max
movinglate_greensboro_annual <- moving_late_greensboro  %>% 
  filter(Original_Data.year >= 2000) %>% 
  group_by(Original_Data.year) %>% 
  summarise(twoday_max_annual = max(Moving_Sum))

#Calculate return period
rp_late_greensboro_moving <- moving_late_greensboro %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(number_events = 2879) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 55 mm

#Plot annual two-day max and return period
ggplot(movinglate_greensboro_annual, aes(x = Original_Data.year, y = twoday_max_annual)) +
  geom_line() +
  geom_smooth(method = "lm") +
  geom_hline(yintercept = 55, color = "red", linetype = "dashed", size = 1) +
  scale_x_continuous(breaks = seq(2000, 2016, 1)) +
  labs(title = "Annual Maximum Two-Day Precipitation Events for Greensboro\nfrom   2000-2016",
       x = "Year",
       y = "Depth of precipitation (mm)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```


```{r Block 3: Greenville 1980-1999 vs 2000-2016}
#Greenville, 1980-1999
early_greenville <- greenville %>% 
  filter(year < 2000)

#Calculate moving sum
moving_sum_early_greenville <- rollapply(early_greenville$Area.Weighted.Mean.Precipitation..mm.per.day., 
                                         width = 2, FUN = sum, fill = NA, 
                                         align = "right")

#Turn into data frame
moving_early_greenville <- data.frame(
  Original_Data = early_greenville,
  Moving_Sum = moving_sum_early_greenville
) %>% 
  filter(Moving_Sum > 0)

#Calculate annual two-day max
movingearly_greenville_annual <- moving_early_greenville  %>% 
  filter(Original_Data.year < 2000) %>% 
  group_by(Original_Data.year) %>% 
  summarise(twoday_max_annual = max(Moving_Sum))

#Calculate return period
rp_early_greenville_moving <- moving_early_greenville %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(number_events = 3393) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 59 mm

#Plot annual two-day max and return period
ggplot(movingearly_greenville_annual, 
       aes(x = Original_Data.year, y = twoday_max_annual)) +
  geom_line() +
  geom_smooth(method = "lm") +
  geom_hline(yintercept = 59, color = "red", linetype = "dashed", size = 1) +
    scale_x_continuous(breaks = seq(1980, 1999, 1)) +
  labs(title = "Annual Maximum Two-Day Precipitation Events for Greenville\n
       from 1980-1999",
       x = "Year",
       y = "Depth of precipitation (mm)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

#Greenville, 1980-1999
late_greenville <- greenville %>% 
  filter(year >= 2000)

#Calculate moving sum
moving_sum_late_greenville <- rollapply(late_greenville$Area.Weighted.Mean.Precipitation..mm.per.day., 
                                        width = 2, FUN = sum, fill = NA, 
                                        align = "right")

#Turn into data frame
moving_late_greenville <- data.frame(
  Original_Data = late_greensboro,
  Moving_Sum = moving_sum_late_greenville
) %>% 
  filter(Moving_Sum > 0)

#Calculate annual two-day max
movinglate_greenville_annual <- moving_late_greenville  %>% 
  filter(Original_Data.year >= 2000) %>% 
  group_by(Original_Data.year) %>% 
  summarise(twoday_max_annual = max(Moving_Sum))

#Calculate return period
rp_late_greenville_moving <- moving_late_greenville %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  mutate(number_events = 2907) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 67 mm

#Plot annual two-day max and return period
ggplot(movinglate_greenville_annual, aes(x = Original_Data.year, y = twoday_max_annual)) +
  geom_line() +
  geom_smooth(method = "lm") +
  geom_hline(yintercept = 67, color = "red", linetype = "dashed", size = 1) +
  scale_x_continuous(breaks = seq(2000, 2016, 1)) +
  labs(title = "Annual Maximum Two-Day Precipitation Events for Greenville\nfrom
       2000-2016",
       x = "Year",
       y = "Depth of precipitation (mm)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r Block 4: Boone hurricanes vs frontal}
#Seasonal, Boone 1980-1999
#Hurricane season
hurricane_boone <- boone %>% 
  filter(month == 7:10) %>% 
  filter(year < 2000)

#Frontal season
frontal_boone <- boone %>% 
  filter(month == 1:6 | month == 11:12) %>% 
  filter(year < 2000)

#Calculate moving sum durring hurricane season
sum_boone_hurricane <- rollapply(
  hurricane_boone$Area.Weighted.Mean.Precipitation..mm.per.day., 
  width = 2, FUN = sum, fill = NA, align = "right")

#Turn into data frame
movingsum_boone_hurricane <- data.frame(
  Original_Data = hurricane_boone,
  Moving_Sum = sum_boone_hurricane
) %>% 
  filter(Moving_Sum > 0)

#Calculate return period
rp_boone_hurricane <- movingsum_boone_hurricane %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  mutate(number_events = 355) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 52 mm

#Calculate moving sum for frontal seaosn
sum_boone_frontal <- rollapply(
  frontal_boone$Area.Weighted.Mean.Precipitation..mm.per.day., 
  width = 2, FUN = sum, fill = NA, align = "right")

#Turn into data frame
movingsum_boone_frontal <- data.frame(
  Original_Data = frontal_boone,
  Moving_Sum = sum_boone_frontal
) %>% 
  filter(Moving_Sum > 0)

#Calculate return period
rp_boone_frontal <- movingsum_boone_frontal %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  mutate(number_events = 723) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 68 mm

#Add new column specifying type
rp_boone_frontal$StormType = "Frontal (1980-1999)"
rp_boone_hurricane$StormType = "Hurricane (1980-1999)"

#Combine into one data set
boone_combined <- bind_rows(rp_boone_frontal, rp_boone_hurricane)

#Plot - 1980-1999 only
ggplot(boone_combined, aes(x = return_period, y = Moving_Sum, color = StormType)) +
  geom_line() +
  labs(title = "Return Period Storms in Boone for Frontal Season 
       and\nHurricane Season, 1980-1999",
       x = "Return Period",
       y = "Depth of precipitation (mm)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 


#Seasonal, boone 2000-2016
#Hurricane season
hurricane_boone_2016 <- boone %>% 
  filter(month == 7:10) %>% 
  filter(year >= 2000)

#Frontal season
frontal_boone_2016 <- boone %>% 
  filter(month == 1:6 | month == 11:12) %>% 
  filter(year >= 2000)

#Calculate moving sum of hurricane season
sum_boone_hurricane_2016 <- rollapply(hurricane_boone_2016$Area.Weighted.Mean.Precipitation..mm.per.day., 
                                      width = 2, FUN = sum, 
                                      fill = NA, align = "right")

#Turn into data frame
movingsum_boone_hurricane_2016 <- data.frame(
  Original_Data = hurricane_boone_2016,
  Moving_Sum = sum_boone_hurricane_2016
) %>% 
  filter(Moving_Sum > 0)

#Calculate return period 
rp_boone_hurricane_2016 <- movingsum_boone_hurricane_2016 %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  mutate(number_events = 319) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 75 mm

#Calculate moving sum of frontal season
sum_boone_frontal_2016 <- rollapply(
  frontal_boone_2016$Area.Weighted.Mean.Precipitation..mm.per.day., 
  width = 2, FUN = sum, fill = NA, align = "right")

#Turn into data frame
movingsum_boone_frontal_2016 <- data.frame(
  Original_Data = frontal_boone_2016,
  Moving_Sum = sum_boone_frontal_2016
) %>% 
  filter(Moving_Sum > 0)

#Calculate return period
rp_boone_frontal_2016 <- movingsum_boone_frontal_2016 %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  mutate(number_events = 595) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 55 mm

#Add new columns to specify storm type
rp_boone_frontal_2016$StormType = "Frontal (2000-2016)"
rp_boone_hurricane_2016$StormType = "Hurricane (2000-2016)"

#Combine all years
boone_combined_all <- bind_rows(rp_boone_frontal, rp_boone_hurricane, 
                                rp_boone_frontal_2016, rp_boone_hurricane_2016)

#Plot
ggplot(boone_combined_all, aes(x = return_period, y = Moving_Sum, color = StormType)) +
  geom_line(size = 1) +
  labs(title = "Return Period Storms in Boone for Frontal Season and\nHurricane Season",
       x = "Return Period (Years)",
       y = "Depth of Precipitation (mm)",
       color = "Storm Type") +
    scale_color_manual(
    values = c("Frontal (1980-1999)" = "#FFCCCC",
               "Frontal (2000-2016)" = "red",
               "Hurricane (1980-1999)" = "#ADD8E6",
               "Hurricane (2000-2016)" = "blue")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```


```{r Block 5: Greensboro hurricanes vs frontal}
#Seasonal, Greensboro 1980-1999
#Hurricane season
hurricane_greensboro <- greensboro %>% 
  filter(month == 7:10) %>% 
  filter(year < 2000)

#Frontal season
frontal_greensboro <- greensboro %>% 
  filter(month == 1:6 | month == 11:12) %>% 
  filter(year < 2000)

#Calculate moving sum of hurricane season
sum_greensboro_hurricane <- rollapply(hurricane_greensboro$Area.Weighted.Mean.Precipitation..mm.per.day., 
                                      width = 2, FUN = sum, fill = NA, 
                                      align = "right")

#Turn into data frame
movingsum_greensboro_hurricane <- data.frame(
  Original_Data = hurricane_greensboro,
  Moving_Sum = sum_greensboro_hurricane
) %>% 
  filter(Moving_Sum > 0)

#Calculate return period
rp_greensboro_hurricane <- movingsum_greensboro_hurricane %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  mutate(number_events = 292) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 51 mm

#Calculate moving sum of frontal season
sum_greensboro_frontal <- rollapply(
  frontal_greensboro$Area.Weighted.Mean.Precipitation..mm.per.day., 
  width = 2, FUN = sum, fill = NA, align = "right")

#Turn into data frame
movingsum_greensboro_frontal <- data.frame(
  Original_Data = frontal_greensboro,
  Moving_Sum = sum_greensboro_frontal
) %>% 
  filter(Moving_Sum > 0)

#Calculate return period
rp_greensboro_frontal <- movingsum_greensboro_frontal %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  mutate(number_events = 634) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 42 mm

#Add columns specifying storm type
rp_greensboro_frontal$StormType = "Frontal (1980-1999)"
rp_greensboro_hurricane$StormType = "Hurricane (1980-1999)"

#Comvine frontal and hurricane
greensboro_combined <- bind_rows(rp_greensboro_frontal, rp_greensboro_hurricane)

#Plot, 1980-1999 only
ggplot(greensboro_combined, aes(x = return_period, y = Moving_Sum, color = StormType)) +
  geom_line() +
  labs(title = "Return Period Storms in Greensboro for Frontal Season 
       and\nHurricane Season, 1980-1999",
       x = "Return Period",
       y = "Depth of precipitation (mm)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

#Seasonal, Greensboro 2000-2016
#Hurricane season
hurricane_greensboro_2016 <- greensboro %>% 
  filter(month == 7:10) %>% 
  filter(year >= 2000)

#Frontal season
frontal_greensboro_2016 <- greensboro %>% 
  filter(month == 1:6 | month == 11:12) %>% 
  filter(year >= 2000)

#Calculate moving sum of hurricane season
sum_greensboro_hurricane_2016 <- rollapply(
  hurricane_greensboro_2016$Area.Weighted.Mean.Precipitation..mm.per.day.,
  width = 2, FUN = sum, fill = NA, align = "right")

#Turn into data frame
movingsum_greensboro_hurricane_2016 <- data.frame(
  Original_Data = hurricane_greensboro_2016,
  Moving_Sum = sum_greensboro_hurricane_2016
) %>% 
  filter(Moving_Sum > 0)

#Calculate return period
rp_greensboro_hurricane_2016 <- movingsum_greensboro_hurricane_2016 %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  mutate(number_events = 285) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 69 mm

#Calculate moving sum of frontal season
sum_greensboro_frontal_2016 <- rollapply(
  frontal_greensboro_2016$Area.Weighted.Mean.Precipitation..mm.per.day., 
  width = 2, FUN = sum, fill = NA, align = "right")

#Turn into data frame
movingsum_greensboro_frontal_2016 <- data.frame(
  Original_Data = frontal_greensboro_2016,
  Moving_Sum = sum_greensboro_frontal_2016
) %>% 
  filter(Moving_Sum > 0)

#Calculate return period
rp_greensboro_frontal_2016 <- movingsum_greensboro_frontal_2016 %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  mutate(number_events = 505) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 42 mm

#Add columns specifying storm type
rp_greensboro_frontal_2016$StormType = "Frontal (2000-2016)"
rp_greensboro_hurricane_2016$StormType = "Hurricane (2000-2016)"

#Combine all years
greensboro_combined_all <- bind_rows(rp_greensboro_frontal, 
                                     rp_greensboro_hurricane, 
                                     rp_greensboro_frontal_2016, 
                                     rp_greensboro_hurricane_2016)

#Plot all years
ggplot(greensboro_combined_all, aes(x = return_period, y = Moving_Sum, 
                                    color = StormType)) +
  geom_line(size = 1) +
  labs(title = "Return Period Storms in Greensboro for Frontal Season 
       and\nHurricane Season",
       x = "Return Period (Years)",
       y = "Depth of Precipitation (mm)",
       color = "Storm Type") +
  scale_color_manual(
    values = c("Frontal (1980-1999)" = "#FFCCCC",
               "Frontal (2000-2016)" = "red",
               "Hurricane (1980-1999)" = "#ADD8E6",
               "Hurricane (2000-2016)" = "blue")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

```


```{r Block 6: Greenville hurricanes vs frontal}
#Seasonal, Greenville 1980-1999
#Hurricane season
hurricane_greenville <- greenville %>% 
  filter(month == 7:10) %>% 
  filter(year < 2000)

#Frontal season
frontal_greenville <- greenville %>% 
  filter(month == 1:6 | month == 11:12) %>% 
  filter(year < 2000)

#Calculate moving sum of hurricane season
sum_greenville_hurricane <- rollapply(hurricane_greenville$Area.Weighted.Mean.Precipitation..mm.per.day., 
                                      width = 2, FUN = sum, fill = NA, 
                                      align = "right")

#Turn into data frame
movingsum_greenville_hurricane <- data.frame(
  Original_Data = hurricane_greenville,
  Moving_Sum = sum_greenville_hurricane
) %>% 
  filter(Moving_Sum > 0)

#Calculate return period
rp_greenville_hurricane <- movingsum_greenville_hurricane %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  mutate(number_events = 296) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 89 mm

#Calculate moving sum of frontal season
sum_greenville_frontal <- rollapply(
  frontal_greenville$Area.Weighted.Mean.Precipitation..mm.per.day., 
  width = 2, FUN = sum, fill = NA, align = "right")

#Turn into data frame
movingsum_greenville_frontal <- data.frame(
  Original_Data = frontal_greenville,
  Moving_Sum = sum_greenville_frontal
) %>% 
  filter(Moving_Sum > 0)

#Calculate return period
rp_greenville_frontal <- movingsum_greenville_frontal %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  mutate(number_events = 623) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 44 mm

#Add columns specifying storm type
rp_greenville_frontal$StormType = "Frontal (1980-1999)"
rp_greenville_hurricane$StormType = "Hurricane (1980-1999)"

#Combine data
greenville_combined <- bind_rows(rp_greenville_frontal, rp_greenville_hurricane)

#Plot, 1980-1999 only
ggplot(greenville_combined, aes(x = return_period, y = Moving_Sum, 
                                color = StormType)) +
  geom_line() +
  labs(title = "Return Period Storms in Greenville for Frontal Season 
       and\nHurricane Season, 1980-1999",
       x = "Return Period",
       y = "Depth of precipitation (mm)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

#Seasonal, greenville 2000-2016
#Hurricane season
hurricane_greenville_2016 <- greenville %>% 
  filter(month == 7:10) %>% 
  filter(year >= 2000)

#Frontal season
frontal_greenville_2016 <- greenville %>% 
  filter(month == 1:6 | month == 11:12) %>% 
  filter(year >= 2000)

#Calculate moving sum of hurricane season
sum_greenville_hurricane_2016 <- rollapply(
  hurricane_greenville_2016$Area.Weighted.Mean.Precipitation..mm.per.day., 
  width = 2, FUN = sum, fill = NA, align = "right")

#Turn into data frame
movingsum_greenville_hurricane_2016 <- data.frame(
  Original_Data = hurricane_greenville_2016,
  Moving_Sum = sum_greenville_hurricane_2016
) %>% 
  filter(Moving_Sum > 0)

#Calculate return period
rp_greenville_hurricane_2016 <- movingsum_greenville_hurricane_2016 %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  mutate(number_events = 280) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 151 mm

#Calculate moving sum of frontal season
sum_greenville_frontal_2016 <- rollapply(frontal_greenville_2016$Area.Weighted.Mean.Precipitation..mm.per.day., 
                                         width = 2, FUN = sum, fill = NA, 
                                         align = "right")

#Turn into data frame
movingsum_greenville_frontal_2016 <- data.frame(
  Original_Data = frontal_greenville_2016,
  Moving_Sum = sum_greenville_frontal_2016
) %>% 
  filter(Moving_Sum > 0)

#Calculate return period
rp_greenville_frontal_2016 <- movingsum_greenville_frontal_2016 %>% 
  filter(Moving_Sum > 0) %>% 
  mutate(rank = rank(-Moving_Sum,
                        ties.method = "max")) %>% 
  mutate(number_events = 460) %>% 
  mutate(weibull = (rank/number_events)) %>% 
  mutate(return_period = 1/weibull)
#moving sum for 50-year 48-hour storm event = 54 mm

#Add columns specifying storm type
rp_greenville_frontal_2016$StormType = "Frontal (2000-2016)"
rp_greenville_hurricane_2016$StormType = "Hurricane (2000-2016)"

#Combine all years
greenville_combined_all <- bind_rows(rp_greenville_frontal, 
                                     rp_greenville_hurricane, 
                                     rp_greenville_frontal_2016, 
                                     rp_greenville_hurricane_2016)

#Plot all years
ggplot(greenville_combined_all, aes(x = return_period, y = Moving_Sum, 
                                    color = StormType)) +
  geom_line(size = 1) +
  labs(title = "Return Period Storms in Greenville for Frontal Season 
       and\nHurricane Season",
       x = "Return Period (Years)",
       y = "Depth of Precipitation (mm)",
       color = "Storm Type") +
  scale_color_manual(
    values = c("Frontal (1980-1999)" = "#FFCCCC",
               "Frontal (2000-2016)" = "red",
               "Hurricane (1980-1999)" = "#ADD8E6",
               "Hurricane (2000-2016)" = "blue")) +
    theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r Block 7: Boone 2016 and 1995 only}
#Boone, 2016
boone_2016 <- boone %>% 
  filter(year == 2016)

#Calculate the moving sum
moving_boone_2016 <- rollapply(
  boone_2016$Area.Weighted.Mean.Precipitation..mm.per.day., width = 2, 
  FUN = sum, fill = NA, align = "right")

#Turn into a data frame
boone_2016_movingsum <- data.frame(
  Original_Data = boone_2016,
  Moving_Sum = moving_boone_2016
) %>% 
  filter(Moving_Sum > 0)

#Calculate two-day monthly max
boone_2016_monthly <- boone_2016_movingsum %>% 
  group_by(Original_Data.month) %>% 
  summarise(twoday_max_monthly = max(Moving_Sum))

#Change month to a factor
boone_2016_monthly$Original_Data.month <- factor(boone_2016_monthly$Original_Data.month, 
       levels = 1:12,
       labels = month.abb)

#Plot the monthly two-day max precip
ggplot(boone_2016_monthly, aes(x = Original_Data.month, y = twoday_max_monthly)) +
  geom_bar(stat = "identity", fill = "skyblue") + 
  labs(title = "Monthly Two-Day Maximum Precipitation, Boone 2016", 
       x = "Month", 
       y = "Depth of Precipitation (mm)") +
  geom_vline(xintercept = 6.5, linetype = "dashed", color = "red", size = 1) +
  geom_vline(xintercept = 10.5, linetype = "dashed", color = "red", size = 1) +
  annotate("text", x = 4.5, y = 60, label = "Hurricane Season", size = 3) +
  annotate("text", x = 8.5, y = 60, label = "Frontal Season", size = 3) +
  theme_bw() 
  
#Boone, 1995
boone_1995 <- boone %>% 
  filter(year == 1995)

#Calculate the moving sum
moving_boone_1995 <- rollapply(
  boone_1995$Area.Weighted.Mean.Precipitation..mm.per.day., width = 2, 
  FUN = sum, fill = NA, align = "right")

#Turn into a data frame
boone_1995_movingsum <- data.frame(
  Original_Data = boone_1995,
  Moving_Sum = moving_boone_1995
) %>% 
  filter(Moving_Sum > 0)

#Calculate two-day annual max
boone_1995_monthly <- boone_1995_movingsum %>% 
  group_by(Original_Data.month) %>% 
  summarise(twoday_max_monthly = max(Moving_Sum))

#Change month to factor
boone_1995_monthly$Original_Data.month <- factor(boone_1995_monthly$Original_Data.month, 
       levels = 1:12,
       labels = month.abb)
    
#Plot the monthly two-day max precip   
ggplot(boone_1995_monthly, aes(x = Original_Data.month, y = twoday_max_monthly)) +
  geom_bar(stat = "identity", fill = "skyblue") + 
  labs(title = "Monthly Two-Day Maximum Precipitation, Boone 1995", 
       x = "Month", 
       y = "Depth of Precipitation (mm)") +
  geom_vline(xintercept = 6.5, linetype = "dashed", color = "red", size = 1) +
  geom_vline(xintercept = 10.5, linetype = "dashed", color = "red", size = 1) +
  annotate("text", x = 3.5, y = 110, label = "Hurricane Season", size = 3) +
  annotate("text", x = 8.5, y = 110, label = "Frontal Season", size = 3) +
  theme_bw()
```

```{r Block 8: Greensboro 2016 and 1995 only}
#Greensboro, 2016
greensboro_2016 <- greensboro %>% 
  filter(year == 2016)

#Calculate the moving sum
moving_greensboro_2016 <- rollapply(
  greensboro_2016$Area.Weighted.Mean.Precipitation..mm.per.day., width = 2, 
  FUN = sum, fill = NA, align = "right")

#Turn into a data frame
greensboro_2016_movingsum <- data.frame(
  Original_Data = greensboro_2016,
  Moving_Sum = moving_greensboro_2016
) %>% 
  filter(Moving_Sum > 0)

#Calculate two-day annual max
greensboro_2016_monthly <- greensboro_2016_movingsum %>% 
  group_by(Original_Data.month) %>% 
  summarise(twoday_max_monthly = max(Moving_Sum))

#Change month to a factor
greensboro_2016_monthly$Original_Data.month <- factor(
  greensboro_2016_monthly$Original_Data.month, 
       levels = 1:12,
       labels = month.abb)

#Plot the monthly two-day max precip
ggplot(greensboro_2016_monthly, aes(x = Original_Data.month, y = twoday_max_monthly)) +
  geom_bar(stat = "identity", fill = "skyblue") + 
  labs(title = "Monthly Two-Day Maximum Precipitation, Greensboro 2016", 
       x = "Month", 
       y = "Depth of Precipitation (mm)") +
  geom_vline(xintercept = 6.5, linetype = "dashed", color = "red", size = 1) +
  geom_vline(xintercept = 10.5, linetype = "dashed", color = "red", size = 1) +
  annotate("text", x = 3, y = 80, label = "Hurricane Season", size = 3) +
  annotate("text", x = 8.5, y = 80, label = "Frontal Season", size = 3) +
  theme_bw() 
  
#Greensboro, 1995
greensboro_1995 <- greensboro %>% 
  filter(year == 1995)

#Calculate the moving sum
moving_greensboro_1995 <- rollapply(
  greensboro_1995$Area.Weighted.Mean.Precipitation..mm.per.day., width = 2, 
  FUN = sum, fill = NA, align = "right")

#Turn into a data frame
greensboro_1995_movingsum <- data.frame(
  Original_Data = greensboro_1995,
  Moving_Sum = moving_greensboro_1995
) %>% 
  filter(Moving_Sum > 0)

#Calculate two-day annual max
greensboro_1995_monthly <- greensboro_1995_movingsum %>% 
  group_by(Original_Data.month) %>% 
  summarise(twoday_max_monthly = max(Moving_Sum))

#Change month to factor
greensboro_1995_monthly$Original_Data.month <- factor(
  greensboro_1995_monthly$Original_Data.month, 
       levels = 1:12,
       labels = month.abb)
    
#Plot the monthly two-day max precip   
ggplot(greensboro_1995_monthly, aes(x = Original_Data.month, y = twoday_max_monthly)) +
  geom_bar(stat = "identity", fill = "skyblue") + 
  labs(title = "Monthly Two-Day Maximum Precipitation, Greensboro 1995", 
       x = "Month", 
       y = "Depth of Precipitation (mm)") +
  geom_vline(xintercept = 6.5, linetype = "dashed", color = "red", size = 1) +
  geom_vline(xintercept = 10.5, linetype = "dashed", color = "red", size = 1) +
  annotate("text", x = 3, y = 75, label = "Hurricane Season", size = 3) +
  annotate("text", x = 8.5, y = 75, label = "Frontal Season", size = 3) +
  theme_bw()
```

```{r Block 9: Greenville 2016 and 1995 only}
#Greenville, 2016
greenville_2016 <- greenville %>% 
  filter(year == 2016)

#Calculate the moving sum
moving_greenville_2016 <- rollapply(
  greenville_2016$Area.Weighted.Mean.Precipitation..mm.per.day., width = 2, 
  FUN = sum, fill = NA, align = "right")

#Turn into a data frame
greenville_2016_movingsum <- data.frame(
  Original_Data = greenville_2016,
  Moving_Sum = moving_greenville_2016
) %>% 
  filter(Moving_Sum > 0)

#Calculate two-day annual max
greenville_2016_monthly <- greenville_2016_movingsum %>% 
  group_by(Original_Data.month) %>% 
  summarise(twoday_max_monthly = max(Moving_Sum))

#Change month to a factor
greenville_2016_monthly$Original_Data.month <- factor(
  greenville_2016_monthly$Original_Data.month, 
       levels = 1:12,
       labels = month.abb)

#Plot the monthly two-day max precip
ggplot(greenville_2016_monthly, aes(x = Original_Data.month, y = twoday_max_monthly)) +
  geom_bar(stat = "identity", fill = "skyblue") + 
  labs(title = "Monthly Two-Day Maximum Precipitation, Greenville 2016", 
       x = "Month", 
       y = "Depth of Precipitation (mm)") +
  geom_vline(xintercept = 6.5, linetype = "dashed", color = "red", size = 1) +
  geom_vline(xintercept = 10.5, linetype = "dashed", color = "red", size = 1) +
  annotate("text", x = 3, y = 150, label = "Hurricane Season", size = 3) +
  annotate("text", x = 8.5, y = 190, label = "Frontal Season", size = 3) +
  theme_bw() 
  
#Greenville, 1995
greenville_1995 <- greenville %>% 
  filter(year == 1995)

#Calculate the moving sum
moving_greenville_1995 <- rollapply(
  greenville_1995$Area.Weighted.Mean.Precipitation..mm.per.day., width = 2, 
  FUN = sum, fill = NA, align = "right")

#Turn into a data frame
greenville_1995_movingsum <- data.frame(
  Original_Data = greenville_1995,
  Moving_Sum = moving_greenville_1995
) %>% 
  filter(Moving_Sum > 0)

#Calculate two-day annual max
greenville_1995_monthly <- greenville_1995_movingsum %>% 
  group_by(Original_Data.month) %>% 
  summarise(twoday_max_monthly = max(Moving_Sum))

#Change month to factor
greenville_1995_monthly$Original_Data.month <- factor(
greenville_1995_monthly$Original_Data.month, 
       levels = 1:12,
       labels = month.abb)
    
#Plot the monthly two-day max precip   
ggplot(greenville_1995_monthly, aes(x = Original_Data.month, y = twoday_max_monthly)) +
  geom_bar(stat = "identity", fill = "skyblue") + 
  labs(title = "Monthly Two-Day Maximum Precipitation, Greenville 1995", 
       x = "Month", 
       y = "Depth of Precipitation (mm)") +
  geom_vline(xintercept = 6.5, linetype = "dashed", color = "red", size = 1) +
  geom_vline(xintercept = 10.5, linetype = "dashed", color = "red", size = 1) +
  annotate("text", x = 3, y = 90, label = "Hurricane Season", size = 3) +
  annotate("text", x = 8.5, y = 90, label = "Frontal Season", size = 3) +
  theme_bw()
```